---
title: "SVM"
author: "Shenglin"
date: "2015年10月28日"
output: html_document
---

```{r}
fish<-read.table("/Users/sheng/Documents/NCCU/ML/NCCU_ML_Note/lab/20151014_fish.txt",h=T)
library(e1071)
s<-svm(fish[,2:7],fish[,1])
summary(s)
pred<-predict(s,fish[,2:7])
table(pred,fish[,1])

s1<-svm(fish[,2:7],fish[,1],gamma=1)
pred1<-predict(s1,fish[,2:7])
table(pred1,fish[,1])

## apparent error rate 先降低 true 才有機會
s5<-svm(fish[,2:7],fish[,1],gamma=120)
pred5<-predict(s5,fish[,2:7])
table(pred5,fish[,1])
       
## Let's start with (cost=0.1,gamma=0.1):
f <- function(c,r){
  c1 <- svm(fish[,2:7],fish[,1],cost=c,gamma=r,cross=148)
  summary(c1)}

optimize(f, c(0, 1), tol = 0.0001, a = 1/3)
xmin

c1<-svm(fish[,2:7],fish[,1],cost=8000,gamma=0.3,cross=148)
c1$tot.accuracy
c2<-svm(fish[,2:7],fish[,1],cost=0.1,gamma=0.1,cross=148)
summary(c1)

```

```{r}
result <- expand.grid(c=seq(100,10000,100),gamma=seq(0,2,0.1))
result$acc <- 0
for(i in 1:2100){
  c1 <- svm(fish[,2:7],fish[,1],cost=result[i,1],gamma=result[i,2],cross=148)
  result$acc[i] <- c1$tot.accuracy
}

result %>% ggplot(aes(x=c,y=gamma,z=acc))+stat_contour(aes(colour=..level..)) -> z1
direct.label(z1)
```

